### ISSUE TITLE
翻译改进

### ISSUE THREAD

**Issue by gekka200** [Exsper/mapping-tools-cn#1]
谱面清洁器 → 谱面**清除**器

滑条绘图器的tips → 程序将导入的图像转换为滑条 → 程序**可**将导入的图像转换为滑条
要开始 → **若**要开始
点击浏览按钮选择一个图像 → **首先**点击浏览按钮选择一个图像
直到显示满意 → 直到合适

滑条补完器的tips → 检查工具提示 → 将鼠标停靠至详细工具上 （变速器那边的最后一句也差不多改一下）

元数据管理器的tips → 为**需要**一一编辑或者把一一直接改成需要
Combo色彩工作室 → Combo**颜色**工作室

Pattern 展览馆 → 排列展览或者排列相册

**Comment by Exsper** [comment]
✅ 谱面清洁器 → 谱面清除器

✅ 滑条绘图器的tips → 程序将导入的图像转换为滑条 → 程序可将导入的图像转换为滑条
✅ 要开始 → 若要开始
✅ 点击浏览按钮选择一个图像 → 首先点击浏览按钮选择一个图像
✅ 直到显示满意 → 直到合适

✅ 滑条补完器的tips → 检查工具提示 → 将鼠标停靠至详细工具上 （变速器那边的最后一句也差不多改一下）

✅ 元数据管理器的tips → 为需要一一编辑或者把一一直接改成需要
✅ Combo色彩工作室 → Combo颜色工作室

✅ Pattern 展览馆 → 排列展览或者排列相册

**Comment by Exsper** [comment]
已应用修改
https://github.com/Exsper/mapping-tools-cn/commit/7bb65e1655eb4b7321e3f2dcf596eafd962f4a64
